version: '3'
name: 'factorio'

services:
  factorio:
    build: https://github.com/laczbali/factorio-server.git
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
    environment:
      SERVER_DEF_NAME: MyServer
      SERVER_DEF_PASSWORD: MyPassword
    volumes:
      - /home/USER/factoriodata:/gamedata
